//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGradoUtap2019.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Aire
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Temperatura { get; set; }
        public string Consumo_mes { get; set; }
        public string Ultima_Revision { get; set; }
        public string Proxima_Revision { get; set; }
        public string Estado_Motor { get; set; }
    }
}
